### ISSUE TITLE
FunctionInfo.long_name misses first parenthesis for Python functions

### ISSUE THREAD

**Issue by tobias-klein** [terryyin/lizard#106]
When running lizard on python code the resulting FunctionInfo objects are missing a parenthesis for the long_name attribute.

Given the following function

```
def test(a, b, c):
    return a+b+c
```

lizard returns "test a , b , c )" instead of "test ( a , b , c )" for FunctionInfo.long_name.

**Comment by terryyin** [comment]
@tobias-klein sorry for the long waiting. I've fix the issue with the commit https://github.com/terryyin/lizard/commit/937c87627373581f10c62de45fb67431b43ae9fd

Will create a release within a week.

**Comment by tobias-klein** [comment]
Thank you! :+1:

What do you exactly mean when you say "release"? I don't see anything at https://github.com/terryyin/lizard/tags

**Comment by terryyin** [comment]
@tobias-klein I put lizard on Pypi. So that you can install lizard by

    pip install lizard

Then you can use it everywhere in the system. By "release" I mean to publish a new version in PyPi. BTW, I haven't yet this week.

**Comment by tobias-klein** [comment]
Ok - cool! Maybe you can add a note in the Readme (under Installation?) stating that releases are regularly published to the PyPi repository.
