### ISSUE TITLE
C++ Boost and Qt awareness

### ISSUE THREAD

**Issue by rakhimov** [terryyin/lizard#126]
Boost and Qt projects provide handy constructs
like`foreach`, `forever`, `Q_FOREACH`, `BOOST_FOREACH`,
which influence the complexity metrics.
C++11 reduces the need for this kind of macros,
but there are still projects relying on these constructs (Qt especially).

I am opening this issue just to see if there's any interest by the community
in getting Lizard aware of these constructs.

**Comment by terryyin** [comment]
After carefully studied the theory (McCabe's), I found forever shouldn't be counted (this is still an open issue to lizard).
@rakhimov what's your opinion on all sort of foreach loops? What about in other languages?

I think the CCN is mostly about how hard it is to test the function. I guess the question is equal to: would you write one additional test case for testing the foreach collection operation?

**Comment by rakhimov** [comment]
What if the collection is empty.

**Comment by rakhimov** [comment]
This macros bothered me upon working on the nested-structures metric.

**Comment by terryyin** [comment]
Exactly, the good old strategy for testing a collection is "0-1-N".

> This macros bothered me upon working on the nested-structures metric.

Only for the situation where they don't have a bracket following them, right?

**Comment by rakhimov** [comment]
The brackets are irrelevant for the nested structures code
if it doesn't recognize that the previous token is a structure signifier.

Lookin at ``oclint``,
I noticed that the metric you probably thinking about is ``statement nesting depth``.
I tjhink this metric also has its merits,
but ``nested structures`` is about control flow structures.

**Comment by terryyin** [comment]
Ok. Now I see the difference.
But can you give me an example of a statement nesting structure that is neither started by an empty bracket, nor started by a control flow instruction?

**Comment by rakhimov** [comment]
I am a bit confused with the question.
I think you meant *statement nesting depth*.
Well, I can think of evil templates.

**Comment by rakhimov** [comment]
Actually, I take back the template example.
That is an expression not a statement within angle brackets.

**Comment by rakhimov** [comment]
I think I got the question.
Correct me if I am wrong.
Give examples of structures defined with non-compound, single statements.
I can only think of the control flow structures,
so the answer to your question to my knowledge is "no".

**Comment by terryyin** [comment]
Would that lead to a different solution for control flow identification?

**Comment by rakhimov** [comment]
I am not sure what you mean.

**Comment by terryyin** [comment]
I mean is it possible to identify control flow structure by looking for non-bare brackets?

**Comment by rakhimov** [comment]
I don't know where you are getting,
but there is nothing special with control-flow structure signatures
that differentiate them from other statements:

```bnf
token (expr) statement | compound_statement
```
Without knowing the tokens,
you can't identify the control-flow structures.
The brackets are irrelevant,
they are part of the compound statement.

**Comment by terryyin** [comment]
@rakhimov I removed two lines of nested_structure code to pass a test. Do you remember why they were there?

https://github.com/terryyin/lizard/commit/e4c68983d30984e3b4261c86ded3f5024a85c905

**Comment by rakhimov** [comment]
There hasn't been any request or interest for custom control-flow keywords (Qt or Boost),
so I think it is not worth implementing.
Reopen if there's more interest or need in future.
