### ISSUE TITLE
Attribute error in reduce function (lizard_ext.lizardio module)

### ISSUE THREAD

**Issue by mehrdad89** [terryyin/lizard#130]
I run lizardio module and faced this issue regarding calculating the fan_in and fan_out metrics:

`File "/home/emehmeh/venv/lib/python2.7/site-packages/lizard_ext/lizardio.py", line 32, in reduce    `
`    new_funcs = {f.unqualified_name: f for f in fileinfo.function_list}  `
`AttributeError: 'NoneType' object has no attribute 'function_list'    `

**Comment by terryyin** [comment]
I will look at it.

**Comment by terryyin** [comment]
Can you check again now?

**Comment by mehrdad89** [comment]
I checked it again with `lizard version 1.12.4`, still the same problem. 
I think you could add a simple check or catch the exception because you're attempting to access an attribute of a variable that is equal to `None` (in my case that is).

**Comment by mehrdad89** [comment]
@terryyin I will try to write a solution for it (with general fan out included) and make a pull request to you to review it.

**Comment by mehrdad89** [comment]
@terryyin This issue has been referred to on the pull request #133. Therefore, I will close this issue, so we can discuss the optimum way to address this particular problem.
