### ISSUE TITLE
PHP fails to recognise files properly

### ISSUE THREAD

**Issue by jacepatel** [terryyin/lizard#131]
An open source repo with a lot of design patterns below provided for example

when I run lizard, it reads the files but sees no cyclomatic complexity. I insert further conditions into it and it produces no difference in the CC.

Any suggestions or pointers on where to fix this?

https://github.com/domnikl/DesignPatternsPHP

**Comment by terryyin** [comment]
@jacepatel thanks for reporting the bug! I never knew that you can ignore the "?>" in PHP. It's now fixed.

BTW, thanks for the example code. It's really amazingly good.
