### ISSUE TITLE
BUG: Python expression structures and nesting level of tokens/structures

### ISSUE THREAD

**Issue by rakhimov** [terryyin/lizard#141]
Python reutilizes keywords for  list comprehension (`for`, `if`) and ternary operator (`if`, `else`).
the current implementation of the nesting structure count, which depends on the nesting level of tokens,
does not differentiate between expressions or statements for these keywords
and keeps counting the nesting level.

Examples:

``` python
def foo(bar):
  return [x for x in bar if x == 42]

def foo(bar):
  return 42 if bar else -42
```

These examples will produce NS = 2 and 1, respectively, instead of 0.

**Comment by terryyin** [comment]
@rakhimov I have reverse-engineered the nested structure implementation with https://github.com/terryyin/lizard/compare/e4f7ff1889ee...63ceb48a3ea7.

Thanks for your great tests. I had a wonderful journey of test-driven development. Didn't re-implement it for Python though. I think for Python it's just the level of indentations.
