### ISSUE TITLE
Javascript ECMAScript6 not supported.

### ISSUE THREAD

**Issue by milo-hyben** [terryyin/lizard#158]
Any plans to support ES6? Especially arrow functions and new class definitions.

**Comment by mfpiccolo** [comment]
Any update on this issue?

**Comment by datomnurdin** [comment]
any solution so far?

**Comment by terryyin** [comment]
It’s certainly on my todo list with high priority.

**Comment by dhanush** [comment]
Any update on this?

**Comment by terryyin** [comment]
ES6 support added!
