### ISSUE TITLE
"Failed to create process" error running lizard

### ISSUE THREAD

**Issue by steronydh** [terryyin/lizard#168]
I'm getting this when trying to run a pip-installed lizard 1.12.7 no Windows 10. No other error message. I get this even with just 'lizard -h'.

**Comment by rakhimov** [comment]
Looks like system issues:
http://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process

**Comment by steronydh** [comment]
I've updated to Python 3.6 and reinstalled lizard and it seems fine now.
