### ISSUE TITLE
Bug: App never stop when call by groovy or jenkins pipeline shell

### ISSUE THREAD

**Issue by robutcher** [terryyin/lizard#176]
1.call by jenkins pipeline shell like below:
sh returnStatus: true, script: "lizard -f ${CHG_FILE} -W ${WHT_LIST} -l c -l cpp -t 15 > ${ANA_NEW}"
some times liazard runs continuously, never stop;

2.call by groovy shell like below:
def command = ‘’‘lizard -f chg.txt -W wht.txt -l c -l cpp -t 15 > rst.txt’‘’
def proc = command.execute() 
proc.waitFor()   // Wait for the command to finish
.waitFor() never stops, liazard always runs continuously, never stop;

**Comment by terryyin** [comment]
Hi robutcher,

Thanks for reporting. I will look at it soon. For the purpose of debugging, can you remove the “-t 15” parameter and try again?

Terry

**Comment by robutcher** [comment]
I have tried, with or without the “-t 15” parameter makes no difference.

**Comment by terryyin** [comment]
Hi Robutcher,

OK. I will need to see which .c file caused the problem. Is it possible that you manually locate which file caused the problem by removing half of the content in “chg.txt” each time?

I will need that source code to investigate. If it’s not sensitive you can also send me all the code.

Br, Terry

**Comment by robutcher** [comment]
I have tried several times, it seem unrelated to some particular files;
1)call by groovy liazard always runs continuously, never stop; **every times**, can you make a try?
2)call by jenkins pipeline **sometimes** liazard runs continuously, seem unrelated to some particular files, just **sometimes**.

**Comment by rakhimov** [comment]
Have you tried on command-line?

**Comment by robutcher** [comment]
I have tried on command-line, it runs ok.

**Comment by rakhimov** [comment]
So, the question is "What is different between cmd-line and Groovy call?".
Environment?
Any gotchas?
Any Groovy warts to be aware of?

Lizard is probably agnostic how it is being called via the cmd-line entry.

**Comment by terryyin** [comment]
My understanding is with groovy, even removing “-t 15” won’t work. That means it’s not likely to be because of the threading.

Can you capture the stderr also in groovy?

**Comment by robutcher** [comment]
println "return code: ${ proc.exitValue()}"
println "stderr: ${proc.err.text}"
println "stdout: ${proc.in.text}" 

can't execute because the "proc.waitFor()"  never stops, so I can't capture the stderr in groovy.

**Comment by terryyin** [comment]
What about
 sh returnStatus: true, script: “python -mlizard -f ${CHG_FILE} -W ${WHT_LIST} -l c -l cpp -t 15 > ${ANA_NEW}”

**Comment by robutcher** [comment]
I think 
sh returnStatus: true, script: “python -m lizard -f ${CHG_FILE} -W ${WHT_LIST} -l c -l cpp -t 15 > ${ANA_NEW}”
equivalent to “/usr/local/bin/python /usr/local/bin/lizard ......"

It is still running, "root 22114 1 0 Feb09 ? 00:00:00 /usr/local/bin/python /usr/local/bin/lizard -f chgfiles.txt -W whitelizard.txt -l c -l cpp -t 15".

**Comment by rakhimov** [comment]
May this be relevant:
http://stackoverflow.com/questions/5483830/process-waitfor-never-returns

**Comment by robutcher** [comment]
bt of call by jenkins

0x00000038b0c0d6c0 in sem_wait () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.47.el6.x86_64 keyutils-libs-1.4-3.el6.x86_64 krb5-libs-1.9-22.el6.x86_64 libcom_err-1.41.12-11.el6.x86_64 libselinux-2.0.94-5.3.el6.x86_64 openssl-1.0.0-20.el6.x86_64 zlib-1.2.3-27.el6.x86_64
(gdb) bt
#0  0x00000038b0c0d6c0 in sem_wait () from /lib64/libpthread.so.0
#1  0x00007fd43e5ec1e1 in semlock_acquire (self=0x7fd43e18aae0, args=<value optimized out>, kwds=<value optimized out>)
    at /tmp/Python-2.7.13/Modules/_multiprocessing/semaphore.c:317
#2  0x00000000004aa6a8 in call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4352
#3  PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#4  0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7fd43e18d2b0, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=0, kws=0x7fd438002238, kwcount=0, defs=0x0, defcount=0, closure=0x7fd43e18eaa0)
    at Python/ceval.c:3584
#5  0x00000000004a94b8 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4447
#6  call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#7  PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#8  0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7fd43ece4330, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=5, kws=0x7fd447c0a068, kwcount=0, defs=0x7fd43ec1e5b8, defcount=3, closure=0x0)
    at Python/ceval.c:3584
#9  0x000000000050fcd8 in function_call (func=0x7fd43ec32938, arg=0x7fd43e1a0290, kw=0x7fd43ebf87f8) at Objects/funcobject.c:523
#10 0x0000000000419bf7 in PyObject_Call (func=0x7fd43ec32938, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#11 0x00000000004a7a95 in ext_do_call (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4666
#12 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:3028
#13 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#14 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#15 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#16 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#17 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#18 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#19 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7fd43e193db0, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=2, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3584
#20 0x000000000050fbde in function_call (func=0x7fd43e1987d0, arg=0x7fd43ecdc680, kw=0x0) at Objects/funcobject.c:523
#21 0x0000000000419bf7 in PyObject_Call (func=0x7fd43e1987d0, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#22 0x00000000004229cf in instancemethod_call (func=0x7fd43e1987d0, arg=0x7fd43ecdc680, kw=0x0) at Objects/classobject.c:2602
#23 0x0000000000419bf7 in PyObject_Call (func=0x7fd43ee7e460, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#24 0x0000000000477c30 in slot_tp_init (self=0x7fd43e1c7b10, args=0x7fd43e1995d0, kwds=0x0) at Objects/typeobject.c:5806
#25 0x000000000046dd8f in type_call (type=<value optimized out>, args=0x7fd43e1995d0, kwds=0x0) at Objects/typeobject.c:765
#26 0x0000000000419bf7 in PyObject_Call (func=0x1fa8630, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#27 0x00000000004a7ec6 in do_call (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4569
#28 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4374
#29 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#30 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#31 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#32 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#33 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#34 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#35 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#36 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#37 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
---Type <return> to continue, or q <return> to quit---
#38 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#39 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7fd43ec043b0, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=1, kws=0x7fd447c0a068, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#40 0x000000000050fcd8 in function_call (func=0x7fd43ec31140, arg=0x7fd43e19f490, kw=0x7fd43ec74b40) at Objects/funcobject.c:523
#41 0x0000000000419bf7 in PyObject_Call (func=0x7fd43ec31140, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#42 0x00000000004a7a95 in ext_do_call (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4666
#43 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:3028
#44 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#45 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#46 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#47 0x00000000004a95d9 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#48 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#49 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#50 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7fd43ee14d30, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=1, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3584
#51 0x000000000050fbde in function_call (func=0x7fd43ee22b90, arg=0x7fd43e199150, kw=0x0) at Objects/funcobject.c:523
#52 0x0000000000419bf7 in PyObject_Call (func=0x7fd43ee22b90, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#53 0x00000000004229cf in instancemethod_call (func=0x7fd43ee22b90, arg=0x7fd43e199150, kw=0x0) at Objects/classobject.c:2602
#54 0x0000000000419bf7 in PyObject_Call (func=0x7fd43ee7e5f0, arg=<value optimized out>, kw=<value optimized out>)
    at Objects/abstract.c:2547
#55 0x00000000004a0a63 in PyEval_CallObjectWithKeywords (func=0x7fd43ee7e5f0, arg=0x7fd447c0a050, kw=<value optimized out>)
    at Python/ceval.c:4221
#56 0x00000000004e3a12 in t_bootstrap (boot_raw=0x1fa0a40) at ./Modules/threadmodule.c:620
#57 0x00000038b0c077f1 in start_thread () from /lib64/libpthread.so.0
#58 0x00000038b04e570d in clone () from /lib64/libc.so.6

**Comment by robutcher** [comment]
bt of call by groovy

#0  0x00000038b04d8450 in __write_nocancel () from /lib64/libc.so.6
#1  0x00000038b0470d43 in _IO_new_file_write () from /lib64/libc.so.6
#2  0x00000038b04722f5 in _IO_new_do_write () from /lib64/libc.so.6
#3  0x00000038b04709bd in _IO_new_file_xsputn () from /lib64/libc.so.6
#4  0x00000038b0466dcd in fwrite () from /lib64/libc.so.6
#5  0x000000000045c7b7 in string_print (op=<value optimized out>, fp=0x38b079b780, flags=<value optimized out>)
    at Objects/stringobject.c:887
#6  0x0000000000452cd3 in internal_print (op=0x7f13cb1c6918, fp=0x38b079b780, flags=1, nesting=0) at Objects/object.c:315
#7  0x000000000042ffd9 in file_PyObject_Print (v=<value optimized out>, f=0x7f13d4578150, flags=1) at Objects/fileobject.c:110
#8  PyFile_WriteObject (v=<value optimized out>, f=0x7f13d4578150, flags=1) at Objects/fileobject.c:2578
#9  0x000000000049d80b in builtin_print (self=<value optimized out>, args=0x7f13cb5d6790, kwds=<value optimized out>)
    at Python/bltinmodule.c:1684
#10 0x00000000004aa6a8 in call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4352
#11 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#12 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7f13cb6ec3b0, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=3, kws=0x7f13cb629420, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#13 0x00000000004a94b8 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4447
#14 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#15 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#16 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7f13cb64ee30, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=3, kws=0x1822588, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3584
#17 0x00000000004a94b8 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4447
#18 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#19 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#20 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7f13cb5cb830, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=0, kws=0x7f13d447ec88, kwcount=0, defs=0x7f13cb59af68, defcount=1, closure=0x0)
    at Python/ceval.c:3584
#21 0x00000000004a94b8 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4447
#22 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#23 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#24 0x00000000004aaf47 in PyEval_EvalCodeEx (co=0x7f13d4241830, globals=<value optimized out>, locals=<value optimized out>, 
    args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3584
#25 0x00000000004ab052 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>)
    at Python/ceval.c:669
#26 0x00000000004cc1ae in run_mod (fp=0x1704810, filename=0x7fff0c3b7584 "/usr/local/bin/lizard", start=<value optimized out>, 
    globals=0x7f13d452b168, locals=0x7f13d452b168, closeit=1, flags=0x7fff0c3b5ea0) at Python/pythonrun.c:1376
#27 PyRun_FileExFlags (fp=0x1704810, filename=0x7fff0c3b7584 "/usr/local/bin/lizard", start=<value optimized out>, 
    globals=0x7f13d452b168, locals=0x7f13d452b168, closeit=1, flags=0x7fff0c3b5ea0) at Python/pythonrun.c:1362
#28 0x00000000004cc3d7 in PyRun_SimpleFileExFlags (fp=0x1704810, filename=0x7fff0c3b7584 "/usr/local/bin/lizard", closeit=1, 
    flags=0x7fff0c3b5ea0) at Python/pythonrun.c:948
#29 0x0000000000415112 in Py_Main (argc=<value optimized out>, argv=<value optimized out>) at Modules/main.c:640
#30 0x00000038b041ecdd in __libc_start_main () from /lib64/libc.so.6
#31 0x00000000004141f9 in _start ()

**Comment by terryyin** [comment]
Sorry for not being able to help. Any updates?
X

**Comment by terryyin** [comment]
There hasn't been much activity here. Let me close the issue for now.
