### ISSUE TITLE
[Bug] Calculating H5A.c, lizard uses many memory and raise error.

### ISSUE THREAD

**Issue by salphaon** [terryyin/lizard#178]
[H5A.zip](https://github.com/terryyin/lizard/files/843486/H5A.zip)

In H5A.zip, it has H5A.c file which is part of debian vtk package source code.

`bash$lizard H5A.c `

print

================================================
  NLOC    CCN   token  PARAM  length  location  
------------------------------------------------

then, lizard uses a lot of memory. print function name infinitely.

**Comment by salphaon** [comment]
When using http://www.lizard.ws, analyze result well

**Comment by salphaon** [comment]
@rakhimov 
So, why does it work well on the web?

**Comment by rakhimov** [comment]
@salphaon Good point!
I am not sure which version / how lizard is called in the web.
My first guess is that the missing terminator blowing the nesting level stacks.
I am getting MemoryError with 
```bash
  File ".../lizard/lizard.py", line 335, in with_namespace
    return ''.join([x.name_in_space for x in self.nesting_stack] + [name])
```

**Comment by rakhimov** [comment]
@terryyin I think this is design hint to separate the "namespace" stack from the "nesting stack".
Currently, the nesting stack is playing a dual role by assuming that the code is syntactically sane.

**Comment by rakhimov** [comment]
@terryyin Alternatively, the nesting stack should be restored to the same state at the function enter/exit
without assuming that the code is balances itself.

**Comment by terryyin** [comment]
@salphaon the lizard used by the web is a bit old. The bug is still there, I'm still investigating. I'm guessing related to the nesting stack.

**Comment by terryyin** [comment]
The bug is now fixed, with a new PyPI version created.

In a nested structure, when there's a macro call with no semicolon ending, all the non-nested structures need to be popped out of the stack @rakhimov 

thanks @salphaon for reporting it.
