### ISSUE TITLE
What means token in results?

### ISSUE THREAD

**Issue by AdamZikmund** [terryyin/lizard#179]
I am using Swift. I want to ask what means tokens in results ? 
`public func getResults() -> Any? {
        return results
    }`
This method generate 6 tokens
`private func passDictionary(dictionary: [String : String]) {
        var mutable = dictionary
        let string = UUID().uuidString
        mutable[string] = string
        results = dictionary
    }`
And this 43

**Comment by terryyin** [comment]
Hi Adam,

Tokens here mean the words, operators or constants.  The result doesn’t count the method declaration though, so the first one got 6 (“any, ?, {, return, results, }”).

Terry

**Comment by AdamZikmund** [comment]
Thank you, very much :)
