### ISSUE TITLE
Stylesheet loading fails because of location change.

### ISSUE THREAD

**Issue by rasjani** [terryyin/lizard#180]
When viewing the xml report in the browser (atleast firefox) - viewing fails because location of the xsl file in the xml is "wrong" eg, there's 301 redirection to https://raw.githubusercontent.com/terryyin/lizard/master/lizard.xsl where the original is https://raw.github.com/terryyin/lizard/master/lizard.xsl

**Comment by kskrishnan** [comment]
Hi, can you please fix this?

**Comment by terryyin** [comment]
Sorry for the late fix. Done. and a new version deployed to Pypi too.
