### ISSUE TITLE
sh: lizard command not found, but lizard is installed

### ISSUE THREAD

**Issue by palusik86** [terryyin/lizard#185]
Hi

I have an issue with lizard. Called via 
`sh("cd .. && lizard ./#{scheme}/ -l swift --xml > ./build/#{scheme}.reports/lizard-report.xml")`
in Jenkins job returns: `sh: lizard: command not found`

But when used via terminal everything works. Has anyone here had similar problem and can share some hints how to solve it ?

**Comment by terryyin** [comment]
Hi @pawelp,

How and on which platform did you installed lizard? It looks like lizard isn’t installed for the Jenkins user (usually called jenkins on linux).

Terry

**Comment by palusik86** [comment]
Hi @terryyin 

So lizard is installed using `sudo` on macOS Sierra. It was working before, but I've updated Jenkins and all the plugins installed. Now I'm trying to figure out why jenkins job is not seeing lizard. Also tried to reinstall lizard without sudo, no result.

**Comment by terryyin** [comment]
Do you run your Jenkins as a separate user? Do you use the home brew python or the system python? Just a few thing that might help you:-)
