### ISSUE TITLE
/usr/local/bin/lizard: error: unrecognized arguments: --csv

### ISSUE THREAD

**Issue by datomnurdin** [terryyin/lizard#186]
I can generate csv file. This is my command

```
lizard /Users/ZERO/Documents/Github/my-python --csv  
```

Error message

```
usage: lizard [options] [PATH or FILE] [PATH] ...
/usr/local/bin/lizard: error: unrecognized arguments: --csv
```

Please advice. Thank you.

**Comment by rakhimov** [comment]
@datomnurdin This feature has been introduced recently.
Are you using the current development version from GitHub or installing from PyPI?

**Comment by datomnurdin** [comment]
Installing via PyPI.

**Comment by terryyin** [comment]
Busy week… I will create a new release to include this new feature soon… while I’m landed in Beijing… and get proper internet connection.

**Comment by datomnurdin** [comment]
Thanks @terryyin .
