### ISSUE TITLE
[new] counts the max depth Functions

### ISSUE THREAD

**Issue by robutcher** [terryyin/lizard#187]
now counter needed
the max depth Functions

**Comment by rakhimov** [comment]
@robutcher Can you clarify what you mean by 'deapth'?

Lizard already has 'nesting CCN depth' and 'depth of nested control-flow structures',
which count the complexity of nesting 'if { while { for {....', for example.
Take a look at #69

**Comment by rakhimov** [comment]
@terryyin I suggest closing this issue as duplicate.
