### ISSUE TITLE
Add new counter : max depth of function

### ISSUE THREAD

**Issue by robutcher** [terryyin/lizard#193]
would you add a new counter ?
max depth of function

**Comment by rakhimov** [comment]
@robutcher C'mon this is a duplicate of your #187 (Why are you opening a duplicate?).
You haven't clarified what 'depth' you want.
All the discussion is in #187.

**Comment by rakhimov** [comment]
This is a duplicate of a duplicate : Dupliception :)

**Comment by robutcher** [comment]
sorry, I forgot it.
