### ISSUE TITLE
Lizard can not generate Html report???

### ISSUE THREAD

**Issue by cyw3** [terryyin/lizard#195]
![image](https://user-images.githubusercontent.com/11549103/29315881-13ce0e48-81f8-11e7-88ea-9c1921b31cc0.png)

**Comment by terryyin** [comment]
You are right, it's never implemented.

Want to try?

**Comment by rakhimov** [comment]
Is this a duplicate of #76?

**Comment by cyw3** [comment]
I have implemented Html output by myself.

**Comment by terryyin** [comment]
Send a pull request if you like:-)

**Comment by liaogz82** [comment]
Err... are you going to create a new release for this? `1.14.0` or something?

**Comment by terryyin** [comment]
Will do it by the end of today.

**Comment by terryyin** [comment]
Done.
