### ISSUE TITLE
Type error when using csv output

### ISSUE THREAD

**Issue by Drogglbecher** [terryyin/lizard#196]
Hi,

first of all: Thanks for your work, nice tool :)

However, I got an issue with the csv output. When running on a python file I get all the values for NLOC, CCN, etc. but after that I get the following error (using python 3.6.2, installed lizard via pip):

```python
Traceback (most recent call last):
  File "/usr/bin/lizard", line 11, in <module>
    load_entry_point('lizard==1.12.14', 'console_scripts', 'lizard')()
  File "/usr/lib/python3.6/site-packages/lizard.py", line 984, in main
    if 0 <= options.number < warning_count:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

Thank you
Sebastian

**Comment by terryyin** [comment]
OK. Fixed and created a new version 1.12.15.

Thanks for reporting.
