### ISSUE TITLE
Lizard doesn't handle names in Emoji

### ISSUE THREAD

**Issue by marksands** [terryyin/lizard#197]
I'm using lizard as one tool for SonarQube analysis. The generated XML file is being generated as UTF-8, but a method name in my swift file contains an emoji character, so everything is mad.

It _should_ render as this:

```xml
<item name="💩(...) at iOS/Foo/Bar/baz.swift:288">
    <value>991</value>
    <value>13</value>
    <value>2</value>
</item>
```

But the emoji is not rendered, causing grief between tools.

```xml
<item name="ð(...) at iOS/Foo/Bar/baz.swift:288">
    <value>991</value>
    <value>13</value>
    <value>2</value>
</item>
```

I'm not 100% sure if this is a lizard problem, a sonar-scanner problem, or both.

**Comment by terryyin** [comment]
But why do you do that?... Ok, because you can...

Let me do a test and try to fix it.

**Comment by terryyin** [comment]
Lizard read the source code by itself and I've tested that at least in the xml text output by Lizard the emoji is still there. Lizard does write the xml to a file by itself, so the problem might occured during the writing.

**Comment by marksands** [comment]
@terryyin I gave a bad example. It's not limited to emoji, but characters such as `θ` or `π` as well: https://github.com/krzyzanowskim/CryptoSwift/blob/cf75e33f637ae36a18dc18c813965e03c19d0684/Sources/CryptoSwift/SHA3.swift#L98

**Comment by marksands** [comment]
I'm not a character encoding expert, so my issue may not be 100% related to lizard, but I do know that lizard's XML file output is converting both the emoji and the theta and pi characters to gibberish.

**Comment by terryyin** [comment]
Yup, cannot argue with a swift repo with 4k+ likes.

At least on my Mac, `lizard --xml a.swift > output.xml` still keeps the emoji.

Is it running on a Mac?

**Comment by marksands** [comment]
Interesting.. mine does not. I am on a Mac running version `1.12.7`.

```
<item name="ð(...) at REDACTED.swift:288">
    <value>15</value>
    <value>13</value>
    <value>2</value>
</item>
```

**Comment by terryyin** [comment]
Ah, maybe it's the Python version. Which version do you use?

**Comment by marksands** [comment]
```
 $ python --version
Python 2.7.10
```

**Comment by marksands** [comment]
Aha! I just went through the python3 pip3 dance to get lizard installed and running under python3 and now I'm seeing the proper character sets! That was it!

**Comment by terryyin** [comment]
Thanks for closing this issue. I wasn't sure if I should add unicode source code support for lizard with Python 2.7. Now I decide to postpone it again.

**Comment by marksands** [comment]
@terryyin No problem. We are okay with using python3. Thanks for the tip!
