### ISSUE TITLE
JSON Output Support

### ISSUE THREAD

**Issue by hgn** [terryyin/lizard#200]
Great tool! To be more useful JSON output beside XML/CSV may pitch the use of Lizard. Parsing csv fine, but json.loads(str) is more natural.

**Comment by terryyin** [comment]
Yes, let me do it.

**Comment by liaogz82** [comment]
what is the use case of using json? so far for sonar xml is fine

**Comment by terryyin** [comment]
Eh, guess that's why I still haven't done it.

**Comment by ECNUwyzZL** [comment]
cry...why not support json?

**Comment by itavero** [comment]
The GitLab Code Quality feature supports the Code Climate JSON format out of the box. See [this section](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) in their documentation on adding a "custom" tool for the Code Quality feature.
It would be very nice if Lizard could produce such a format out of the box, so I don't have to write an additional conversion script.
