### ISSUE TITLE
Option to Exclude Switch/Case Cascades

### ISSUE THREAD

**Issue by hgn** [terryyin/lizard#201]
One major cited disadvantage with Cyclomatic Complexity are switch/case statements. Using lizard in larger projects the upper 10% are **valid** switch case statements where you never want to replace this code. Even more: nearly no switch case statement in the analysed code can or will be replaced - they are all fine.

Idea: add an option to exclude switch/case statements from the analysis. Will be helpful for a lot of projects!

**Comment by terryyin** [comment]
I think there is an option already, which is ```—modified```. I think the help message can be improved.

**Comment by hgn** [comment]
Great news! Yes the help message should be extended to understand this aspect. Are there any other side aspects or is it just "remove switch/case" from the statistics?

**Comment by terryyin** [comment]
The only change is counting "switch" instead of counting "case". Yeah, the option "--modified" is a bit over generalisation for something very specific:-)

Will add it to the help and readme.

**Comment by hgn** [comment]
Perfect! Thank you @terryyin
