### ISSUE TITLE
Can lizard detect duplicate code files?

### ISSUE THREAD

**Issue by cyw3** [terryyin/lizard#206]
I use lizard to scan the directory of a file "highcharts.js" a nd its copy.
![image](https://user-images.githubusercontent.com/11549103/33663282-4e1c96a2-daca-11e7-832b-17139a93ed6a.png)

And i find that the result of lizard just show the CCN of highcharts.js and have not the CCN of highcharts2.js.

After i modify the content of highcharts.js.
The result have all CCN of two file.

So, Can lizard detect duplicate code files?

**Comment by terryyin** [comment]
Yes, lizard will not do the analysis again if the file’s MD5 hash is identical.
