### ISSUE TITLE
Kotlin support for lizard?

### ISSUE THREAD

**Issue by mosesliao** [terryyin/lizard#222]
Hi. Any plans for lizard to be used for kotlin?

**Comment by liaogz82** [comment]
Kotlin is like swift. I guess we see first. If there is no thumbs up, I will not develop one

**Comment by terryyin** [comment]
Hey,

A late happy birthday and sorry for the super late reply:P

Lizard use a manually created state-machine (not an AST) to parse code. And each language has a bit special states, here’s the swift specific states:
https://github.com/terryyin/lizard/blob/master/lizard_languages/swift.py <https://github.com/terryyin/lizard/blob/master/lizard_languages/swift.py>

**Comment by iccen8** [comment]
Since Kotlin is getting more and more popular in Android development (official android development language), Kotlin support for Lizard will be necessary. 
Hope to see Kotlin's support soon :D

**Comment by cyw3** [comment]
Hope to see Kotlin's support soon.

**Comment by terryyin** [comment]
Let me learn Kotlin first...

**Comment by liaogz82** [comment]
as I have said before Kotlin is very similar to swift. Just think like swift and you will get there easily

**Comment by liiri** [comment]
Hiya all,
I'm very invested in supporting Kotlin, but am not very familiar with the language. If anyone that's also familiar with Lizard low-level can assist me with a few questions in the integration I'd be happy to make a pull request :)
