### ISSUE TITLE
Lizard is having issue with Parametrizable class Syntax

### ISSUE THREAD

**Issue by arpitx165** [terryyin/lizard#226]
If we add code, where the class type can be Parametrizable then Lizard gives wrong complexity sometimes it doesn't give complexity(Return Empty).

` Class<?>[] testClasses = {String.class};`

Why is `?` treating as a decision point?

Edit : 

Example - for the below Java code  

     class demo{

     public void test(){

     Class<?>[] testClasses = {String.class};

     }

     public void test1(){
 
     Class<?>[] testClasses = {String.class};

      }

     }
`
Result :  

> {'cyclomatic_complexity': 2, 'token_count': 20, 'name': 'demo::demo::test.test1', 'parameters': [], 'fan_out': 0, 'top_nesting_level': 2, 'filename': 'demo.java', 'nloc': 4, 'long_name': 'demo::demo::test.test1()', 'length': 6, 'end_line': 16, 'start_line': 11, 'general_fan_out': 0, 'fan_in': 0}

Why both functions are not coming?

**Comment by terryyin** [comment]
Oh, that’s because it took the ? as the ternary operator!

Let me try to fix this.

**Comment by terryyin** [comment]
I fixed it but with a very specific solution. It only works for <?>. Is it good enough?

**Comment by arpitx165** [comment]
@teryyin Yes that's fine but it's generalized solutions when we pass wildcard characters (for example : ?, * etc. )

**Comment by terryyin** [comment]
But ? is the one making trouble here. So I will call it a good enough solution for now. Included in a release already.

**Comment by arpitx165** [comment]
@terryyin Okay fine.If i find any problem then i will share with you  :)
