### ISSUE TITLE
  CCN reports increctly for func_b  because of  func_a "Nested #if"

### ISSUE THREAD

**Issue by FanJianming** [terryyin/lizard#229]
void func_a()
{

int a =1;
int b =2;

#if 0
#ifdef _DEBUG_
                    if(b > a)
                    {
                        #if 0
                        if(flr_stat_operation_flag ==TRUE)
                        {
                        }
                        else
                        {
                        #endif
                        printf("%s","a>b");

                        //}

                    }
#else
         printf("%s","aaa");
#endif
#endif

}

void func_b(int b)
{
 int a=2;
 int b=3;
 if (a > b) printf("%s","a>b");

}

**Comment by terryyin** [comment]
Yes. Lizard still cannot do preprocessing.

So, in a way, Lizard is counting how complicated the code “looks” from a reader’s perspective gathering from a compiler’s perspective. That’s not entirely true because sometime Lizard counts the wrong function because the brackets in preprocessor.
