### ISSUE TITLE
the result between xml format  result and no format output is different

### ISSUE THREAD

**Issue by gucj** [terryyin/lizard#232]
**at the same git repository dir,the result of different format is different.**
`<average label="NCSS" value="15.577027027027027"/>  != Avg.NLOC 12.1 `
**run lizard  -X >>result.xml**
the summary result is:
`		<average label="NCSS" value="106.73148148148148"/>

		<average label="CCN" value="21.25"/>

		<average label="Functions" value="6.851851851851852"/>

		<sum label="NCSS" value="11527"/>

		<sum label="CCN" value="2295"/>

		<sum label="Functions" value="740"/>

		<average label="NCSS" value="15.577027027027027"/>

		<average label="CCN" value="3.1013513513513513"/>
`

**run lizard   >>result.txt**
the summary result is:

`
==========================================================================================
Total nloc   Avg.NLOC  AvgCCN  Avg.token   Fun Cnt  Warning cnt   Fun Rt   nloc Rt
------------------------------------------------------------------------------------------
     11527      12.1     3.1       79.6      740           17      0.02    0.22
`

**Comment by terryyin** [comment]
Hi Mr.灰太狼,

Thanks! I found the problem. In the XML the average include source code that is not in any function. I will change it to the same as text output.

Terry

**Comment by terryyin** [comment]
OK. Fixed and a new release is created.
