### ISSUE TITLE
Problems to install 1.15.5 from source 

### ISSUE THREAD

**Issue by davidlange6** [terryyin/lizard#235]
Hi

While trying to install lizard 1.15.5 from source (downloaded from pypi) I run into 

[dlange@cmsdev14 lizard-1.15.3]$ python setup.py install --install-dir=$PWD/../lt1
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    with codecs.open(changes, encoding='utf-8') as changes:
  File "/usr/lib64/python2.6/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/build/dlange/180725/att/lizard-1.15.3/CHANGELOG.md'

which indeed there is no CHANGELOG.md in the tar ball.

Thanks for any help.

**Comment by terryyin** [comment]
@davidlange6 oh, I've never tried to download from pypi and install from source.

I've created a new package 1.15.6. Could you please try again?

**Comment by davidlange6** [comment]
Thanks - I confirm this works.
