### ISSUE TITLE
Extending CodeReader combined symbols for bit shift operations

### ISSUE THREAD

**Issue by benolayinka** [terryyin/lizard#252]
I'm trying to add bit shift and assign operations to the list of combined symbols in CodeReader, namely
>>= and <<=.

I added them to the list of combined symbols in CodeReader, but when I print the list of tokens, instances of >>= appear as '>>', '='

The regex is a bit over my head as is, do you have any suspicion why this isn't working?

**Comment by terryyin** [comment]
Have you tried to change the order of these symbols in the regex? If a “=“ is before “<<=“, the later one will never match.

**Comment by benolayinka** [comment]
Yep, I added >>= and <<= to the beginning of the list. I also tried removing other tokens from the list and it didn't seem to affect the tokenization. With the list unmodified, I would expect '>>=' to be tokenized as '>' and '>=' since you have '>=' as a token, but that is also not happening.

**Comment by terryyin** [comment]
Do you have a fork or somewhere I can see the code?

**Comment by benolayinka** [comment]
I pushed my fork, [here's ](https://github.com/benolayinka/lizard/commit/4784fcda45b2299d16a7bf71edbcd8db2160e00d#diff-c34d2ca653e2b9d4862b3f159389f78b) the commit history. I added ">>=" as the first symbol in the "combined_symbols" list in code_reader.py.

In lizard.py, I also attach the tokens to the FileInfo object in your analyze_source_code function so I can see it in the console.

```
>>> i = lizard.analyze_file.analyze_source_code("AllTests.cpp", "int foo(){x>>=10")
>>> i.tokens
['int', ' ', 'foo', '(', ')', '{', 'x', '>>', '=', '10']
```

From code_reader.py:

```
combined_symbols = [">>=", "||", "&&", "===", "!==", "==", "!=", "<=",
                                ">=", "->",
                                "++", "--", '+=', '-=',
                                '*=', '/=', '^=', '&=', '|=', "..."]
```

**Comment by terryyin** [comment]
I tried your code, seems it works fine. Did you import your local copy of lizard or imported the globally installed one?

**Comment by benolayinka** [comment]
It's working for me now too. I think that reload wasn't actually reloading the module, I'm not sure why. I appreciate your help, your tool is fantastic.
