### ISSUE TITLE
Latest release made it considerably slower

### ISSUE THREAD

**Issue by ishepard** [terryyin/lizard#253]
Hi @terryyin,
thank you for the tool, very cool and useful! 

I have a small remark though: with the latest release, the tool became considerably slower. As a test, I called `lizard.analyze_file.analyze_source_code()` on 3910 files, and these are the statistics:

```
# lizard v1.15.7
Analyzed 3910 files in 0:2:25 

# lizard v1.16.1
Analyzed 3910 files in 0:24:40 
```

As you can see, we moved from 2 minutes to 24 😕 

Not an urgent problem, I am gonna stick with Lizard==1.15.7, but just to let you know 😄

**Comment by terryyin** [comment]
Well, that is not acceptable. Thanks for letting me know. I will revert and make a new version and then test the new feature again before releasing.

**Comment by terryyin** [comment]
It will be great if you can confirm that 1.16.2 has restore the speed.

**Comment by ishepard** [comment]
Mmm nope the problem seems to be still there.

**Comment by ishepard** [comment]
As an example, I downloaded this file: https://raw.githubusercontent.com/google/jsonnet/master/cmd/jsonnet.cpp

and then:
```
# Lizard 1.16.2
> time lizard jsonnet.cpp
.....
lizard jsonnet.cpp  8.62s user 0.02s system 99% cpu 8.659 total
```
```
# Lizard 1.15.7
> time lizard jsonnet.cpp
...
lizard jsonnet.cpp  0.08s user 0.01s system 96% cpu 0.097 total
```

As you can see, 8 seconds instead of 0.08

**Comment by terryyin** [comment]
OK. Got the culprit (from a pull request), which is a piece of low performance Regex. Fixed.

**Comment by ishepard** [comment]
Yes I can confirm it, the problem has been fixed! Thank you for your fast replies 😄

**Comment by terryyin** [comment]
Thanks again for reporting this.
