### ISSUE TITLE
Module Usage (lizard.analyze_file()) and "--modified" Option

### ISSUE THREAD

**Issue by hgn** [terryyin/lizard#259]
Hello @terryyin, one short question: I want to call `analyze_file()` with the same behavior as I call it as an executable `lizard --modified <path>`. In fact: the switch/case counting is somehow braindead for software quality, so I don't want to count it.

I grepped over the source code but didn't find a way to specify the flag. Any ideas?

Best regards!

**Comment by terryyin** [comment]
Sorry for the late reply.

Try this:
```
analyze_file = FileAnalyzer(get_extensions([‘’modified"]))
```

Then use the analyse_file function. The modified part is implemented in an extension. Sorry, it’s not extremely obvious from the source code.
