### ISSUE TITLE
Perform error

### ISSUE THREAD

**Issue by MoShenGuo** [terryyin/lizard#261]
![image](https://user-images.githubusercontent.com/21171688/54811328-677ba180-4cc3-11e9-8e1b-8db5c92da428.png)
Hello, according to the steps you said error, what reason be?

**Comment by MoShenGuo** [comment]
lizard mySource/ -x"./tests/*" 
hello,Execute the commands, it should be behind the correct statistical problems

**Comment by terryyin** [comment]
I think the order of the path and options doesn't matter.

It seems you have none ascii characters in either for function name or file name. Is that the case? Which version of Python are you using?

(你写中文我也能看懂)

**Comment by MoShenGuo** [comment]
Python version is 2.7

**Comment by terryyin** [comment]
Python 2.7 doesn't handle utf file names well.
