### ISSUE TITLE
Scala parsing issue

### ISSUE THREAD

**Issue by juli1** [terryyin/lizard#264]
There is an error when processing Scala code. In fact, code related to play/slick is being incorrect.

For example, class fields declared like this `def id = column[Long]("id", O.PrimaryKey, O.AutoInc)` are interpreted as functions and not as class fields. This type of pattern is heavily used in play/slick.

As a result, the number of functions/class fields are not reported correctly.

How to reproduce:
1. `git clone https://github.com/playframework/play-scala-slick-example.git`
2. run `lizard` in the cloned directory
3. check errors for the file `./app/models/PersonRepository.scala`. Many methods are missing and the fields being added are incorrect.

**Comment by terryyin** [comment]
Sorry for the super late reply. The Scala support was from a pull request and the implementation wasn't complete. I've improved it to make the support more serious now.
