### ISSUE TITLE
Swift: `for` label name count by ccn

### ISSUE THREAD

**Issue by kijuky** [terryyin/lizard#265]
This code's ccn is 1, but lizard output 2.

```swift
something(for: .something)
```

I think that lizard count `for` label name. So I want that lizard ignore `for` label name when counting ccn.

**Comment by terryyin** [comment]
Yes, this probably can be fixed by ignoring "for:"?

**Comment by kijuky** [comment]
Thank you for your comment!

I tried resolve the issue by PR #265. I have some questions about my solution.

- The right of renaming `for` to `_for`
- The CI will fail anyway by timeout.

...Should I talk in PR #265 ?

**Comment by kijuky** [comment]
Thank you for merging! This issue closed!
