### ISSUE TITLE
Swift: guard clause is not counted by ccn

### ISSUE THREAD

**Issue by kijuky** [terryyin/lizard#267]
This code's ccn is 2, but lizard output 1.

```swift
guard isValid else { return }
```

This code is equal `if isValid { return }`, so I want that lizard output 2.

**Comment by terryyin** [comment]
Yes, I think this should be counted. Would you make the change? Just add a test and make it pass. Otherwise I can fix this by next week.

**Comment by kijuky** [comment]
Thank you for your comment!

I tried to create PR #268 referring to the implementation of parser of other languages.

**Comment by kijuky** [comment]
Thank you for merging! This issue closed!
