### ISSUE TITLE
github.io page is outdated

### ISSUE THREAD

**Issue by marco-c** [terryyin/lizard#277]
E.g. the list of supported languages is much shorter. I would suggest just dropping the page and make it redirect to the repository itself (like http://www.lizard.ws/ does).

**Comment by terryyin** [comment]
where can I find the GitHub.io page?

**Comment by marco-c** [comment]
https://terryyin.github.io/lizard/, it's created automatically from the gh-pages branch of your repository (https://github.com/terryyin/lizard/tree/gh-pages).

**Comment by terryyin** [comment]
Thanks. Now the memory comes back:-) I will update it as your advice.
