### ISSUE TITLE
Support Rust

### ISSUE THREAD

**Issue by marco-c** [terryyin/lizard#278]
It would be nice if lizard supported Rust.

**Comment by terryyin** [comment]
Yeah, I’m looking forward to adding support fr Rust and ES6 this holiday.

**Comment by terryyin** [comment]
I've added support for Rust. Could you please try it a bit? Or can you give me a few example projects to test?

**Comment by marco-c** [comment]
Here are a few example projects:
https://github.com/mozilla/grcov
https://github.com/mozilla/rust-parsepatch
https://github.com/mozilla/dump_syms
https://github.com/serde-rs/serde
https://github.com/rust-lang-nursery/lazy-static.rs
https://github.com/dtolnay/syn
https://github.com/rust-random/rand
https://github.com/rust-lang/libc

**Comment by terryyin** [comment]
ok. I've tested a couple from your list. Looks fine to me. Thanks!
