### ISSUE TITLE
nloc warnings not highlighted in html output

### ISSUE THREAD

**Issue by tobias-klein** [terryyin/lizard#279]
When using the html output with a command like
`lizard -H -Tnloc=50 -Tcyclomatic_complexity=10`
the **nloc threshold warnings are not highlighted in the output**, but only the cyclomatic complexity warnings. This has been tested based on the latest revision from master (`fe1f65046dd26ffebb08de7cf544c146e566862c`).

**Comment by terryyin** [comment]
Thanks for reporting. The bug is fixed.
