### ISSUE TITLE
Version 1.17.1 does not install

### ISSUE THREAD

**Issue by wasilukm** [terryyin/lizard#280]
I'm getting an exception while installing 1.17.1 via pip on Python 2.7
`Building wheels for collected packages: lizard
  Running setup.py bdist_wheel for lizard ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mwasilu\\appdata\\local\\temp\\pip-install-ycdr02\\lizard\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\mwasilu\appdata\local\temp\pip-wheel-py0p1_ --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  copying lizard.py -> build\lib
  creating build\lib\lizard_ext
  copying lizard_ext\auto_open.py -> build\lib\lizard_ext
  copying lizard_ext\csvoutput.py -> build\lib\lizard_ext
  copying lizard_ext\default_ordered_dict.py -> build\lib\lizard_ext
  copying lizard_ext\extension_base.py -> build\lib\lizard_ext
  copying lizard_ext\htmloutput.py -> build\lib\lizard_ext
  copying lizard_ext\keywords.py -> build\lib\lizard_ext
  copying lizard_ext\lizardboolcount.py -> build\lib\lizard_ext
  copying lizard_ext\lizardcomplextags.py -> build\lib\lizard_ext
  copying lizard_ext\lizardcpre.py -> build\lib\lizard_ext
  copying lizard_ext\lizarddependencycount.py -> build\lib\lizard_ext
  copying lizard_ext\lizarddumpcomments.py -> build\lib\lizard_ext
  copying lizard_ext\lizardduplicate.py -> build\lib\lizard_ext
  copying lizard_ext\lizardduplicated_param_list.py -> build\lib\lizard_ext
  copying lizard_ext\lizardexitcount.py -> build\lib\lizard_ext
  copying lizard_ext\lizardignoreassert.py -> build\lib\lizard_ext
  copying lizard_ext\lizardio.py -> build\lib\lizard_ext
  copying lizard_ext\lizardmccabe.py -> build\lib\lizard_ext
  copying lizard_ext\lizardmodified.py -> build\lib\lizard_ext
  copying lizard_ext\lizardnd.py -> build\lib\lizard_ext
  copying lizard_ext\lizardnonstrict.py -> build\lib\lizard_ext
  copying lizard_ext\lizardns.py -> build\lib\lizard_ext
  copying lizard_ext\lizardoutside.py -> build\lib\lizard_ext
  copying lizard_ext\lizardwordcount.py -> build\lib\lizard_ext
  copying lizard_ext\version.py -> build\lib\lizard_ext
  copying lizard_ext\xmloutput.py -> build\lib\lizard_ext
  copying lizard_ext\__init__.py -> build\lib\lizard_ext
  creating build\lib\lizard_languages
  copying lizard_languages\clike.py -> build\lib\lizard_languages
  copying lizard_languages\code_reader.py -> build\lib\lizard_languages
  copying lizard_languages\csharp.py -> build\lib\lizard_languages
  copying lizard_languages\gdscript.py -> build\lib\lizard_languages
  copying lizard_languages\go.py -> build\lib\lizard_languages
  copying lizard_languages\golike.py -> build\lib\lizard_languages
  copying lizard_languages\java.py -> build\lib\lizard_languages
  copying lizard_languages\javascript.py -> build\lib\lizard_languages
  copying lizard_languages\js_style_language_states.py -> build\lib\lizard_languages
  copying lizard_languages\js_style_regex_expression.py -> build\lib\lizard_languages
  copying lizard_languages\lua.py -> build\lib\lizard_languages
  copying lizard_languages\objc.py -> build\lib\lizard_languages
  copying lizard_languages\php.py -> build\lib\lizard_languages
  copying lizard_languages\python.py -> build\lib\lizard_languages
  copying lizard_languages\ruby.py -> build\lib\lizard_languages
  copying lizard_languages\rubylike.py -> build\lib\lizard_languages
  copying lizard_languages\rust.py -> build\lib\lizard_languages
  copying lizard_languages\scala.py -> build\lib\lizard_languages
  copying lizard_languages\script_language.py -> build\lib\lizard_languages
  copying lizard_languages\swift.py -> build\lib\lizard_languages
  copying lizard_languages\tnsdl.py -> build\lib\lizard_languages
  copying lizard_languages\ttcn.py -> build\lib\lizard_languages
  copying lizard_languages\__init__.py -> build\lib\lizard_languages
  installing to build\bdist.win32\wheel
  running install
  running install_lib
  creating build\bdist.win32
  creating build\bdist.win32\wheel
  copying build\lib\lizard.py -> build\bdist.win32\wheel\.
  creating build\bdist.win32\wheel\lizard_ext
  copying build\lib\lizard_ext\auto_open.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\csvoutput.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\default_ordered_dict.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\extension_base.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\htmloutput.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\keywords.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardboolcount.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardcomplextags.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardcpre.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizarddependencycount.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizarddumpcomments.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardduplicate.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardduplicated_param_list.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardexitcount.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardignoreassert.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardio.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardmccabe.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardmodified.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardnd.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardnonstrict.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardns.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardoutside.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\lizardwordcount.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\version.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\xmloutput.py -> build\bdist.win32\wheel\.\lizard_ext
  copying build\lib\lizard_ext\__init__.py -> build\bdist.win32\wheel\.\lizard_ext
  creating build\bdist.win32\wheel\lizard_languages
  copying build\lib\lizard_languages\clike.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\code_reader.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\csharp.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\gdscript.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\go.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\golike.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\java.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\javascript.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\js_style_language_states.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\js_style_regex_expression.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\lua.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\objc.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\php.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\python.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\ruby.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\rubylike.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\rust.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\scala.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\script_language.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\swift.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\tnsdl.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\ttcn.py -> build\bdist.win32\wheel\.\lizard_languages
  copying build\lib\lizard_languages\__init__.py -> build\bdist.win32\wheel\.\lizard_languages
  running install_data
  creating build\bdist.win32\wheel\lizard-1.17.1.data
  creating build\bdist.win32\wheel\lizard-1.17.1.data\data
  creating build\bdist.win32\wheel\lizard-1.17.1.data\data\lizard_ext
  error: can't copy 'lizard_ext\template.html': doesn't exist or not a regular file`

**Comment by vilvo** [comment]
I resolved this in the meanwhile with 
`git clone https://github.com/terryyin/lizard.git`
`cd lizard`
`git checkout 1.17.0`
`python -m pip install .`

**Comment by terryyin** [comment]
Oops, sorry. Fixed.
