### ISSUE TITLE
Misinterprets parameter default value as parameter identifier

### ISSUE THREAD

**Issue by trouvant** [terryyin/lizard#290]
Analysis of a python file containing, for instance, the function
```py
def test(lorem, ipsum = 14, dolor=None):
...
```
yields a `FunctionInfo` object with field `parameters: ['lorem', '14', 'None']` rather than the expected `parameters: ['lorem', 'ipsum', 'dolor']`. This occurs across languages.

**Comment by terryyin** [comment]
I see. Trying to fix...

**Comment by terryyin** [comment]
OK. This is fixed. Thanks for reporting!
