### ISSUE TITLE
Wrong line # reported when '\' is used in C macro

### ISSUE THREAD

**Issue by sungwoonpark** [terryyin/lizard#307]
Hello.

Thanks for developing such great tool.

While I was using it in my code, I found the lizard report wrong line # sometimes. It happens when '\' was used in macro. 
As you can see below example, foo function is located at line 8, but the tool reported as line 3.

Can you take a look at this?

command : python3.7 lizard-1.17.7/lizard.py -Ecpre --xml hello.c > hello.c.xml

Here is hello.c
`#define mymacro(_value)                             \\
{                                                   \\
    if (_typeSize == 2)                             \\
        _value = htobe64(_value);                   \\
    }                                               \\
}

void foo(void)
{
    int i=0;
    i++;
}
`

Here is Lizard output(hello.c.xml)
`        <item name="foo(...) at hello.c:3">
            <value>1</value>
            <value>5</value>
            <value>1</value>      
`

**Comment by sungwoonpark** [comment]
Hmm.. github deleted all '\' in the macro. from the starting line to end line of the mymacro, there is '\' at end of the line.

**Comment by terryyin** [comment]
Thanks. This seems to be a bug. I will find time to fix it.

**Comment by terryyin** [comment]
Sorry for the long wait. This is fixed by https://github.com/terryyin/lizard/commit/42cc021aaf0346663101a4bad5e5bada170a7e6e.
