### ISSUE TITLE
Failed to detect abstract methods without method body in Java.

### ISSUE THREAD

**Issue by cg122** [terryyin/lizard#308]
Code metrics do not make much sense for abstract methods without method body. Is it an intentional design to not return results for any abstract methods in Java? But it should be taken into consideration for file level metrics. 

Failed following test added in testJava.py:

```
    def test_abstract_function_without_body(self):
        result = get_java_function_list("abstract void fun();")
        self.assertEqual(1, len(result))
```

**Comment by terryyin** [comment]
Hi @cg122 , do you mean an abstract method should be counted as 1 function?
