### ISSUE TITLE
Failed to detect method following an abstract method that does not have method body but with 'throws' in Java

### ISSUE THREAD

**Issue by cg122** [terryyin/lizard#309]
See the following failed test case added to testJava.py:

```
    def test_abstract_function_without_body_with_throws_following_method(self):
        result = get_java_function_list("abstract void fun() throws e; void fun2(){}")
        self.assertEqual("fun", result[0].name)          # passed
        self.assertEqual(2, len(result))                 # failed
```
Result function list includes `fun`, but not `fun2`. `fun2` is considered part of `fun()`.

If no throws in abstract method:
```
    def test_abstract_function_without_body_following_method(self):
        result = get_java_function_list("abstract void fun(); void fun1(){}")
        self.assertEqual("fun1", result[0].name)         # passed
        self.assertEqual(2, len(result))                 # failed
```

Result function list includes `fun1`, but not `fun`.

**Comment by terryyin** [comment]
Hmmm, I agree with you. Abstract method shouldn’t be counted. And not dealing with the abstract keyword lead to this bug.

**Comment by terryyin** [comment]
This is fixed by https://github.com/terryyin/lizard/commit/4891f116489fc5ae9cab781da1264352ad00e749
