### ISSUE TITLE
Incomplete method name when class definition has generics as type with extends in Java

### ISSUE THREAD

**Issue by cg122** [terryyin/lizard#310]
Please see the following failed test:

```
def test_generic_type_with_extends(self):
        result = get_java_function_list("class B<T extends C> {void fun(T t) {}}")
         # actual "B<T::fun"
        self.assertEqual("B<T>::fun", result[0].name) 
```

**Comment by terryyin** [comment]
@cg122 hmm, what about removing the template part to make it like `B::fun`? Would it be good enough?

**Comment by cg122** [comment]
@terryyin I think it would be enough as we are also trying to keep function name the simplest form.

**Comment by terryyin** [comment]
This one is fixed and I will look at the others soon.
