### ISSUE TITLE
Java CCN issue with bounded wildcards

### ISSUE THREAD

**Issue by MarcW1g** [terryyin/lizard#323]
When the following code snippet is evaluated, the `?` in `Class<? extends String>` is counted as a condition (thus, adding 1 to the CCN). This results in the following method:
```java
void A(){
    List<?> list = new ArrayList<Set<Class<? extends String>>>();
}
```
having a Cyclomatic Complexity of 2, even though this should be 1.

**Comment by terryyin** [comment]
Thanks for the report. It was very easy to reproduce this in a test.

This bug is fixed now.
