### ISSUE TITLE
Fail brew install on XcodeCloud

### ISSUE THREAD

**Issue by KeimyPlaza** [terryyin/lizard#384]
Since one month or more before I'd a Worflow on XcodeCloud for IC using brew lizard-analyzer.

Since 3 or 4 days is working wrong.

I review the last log of CI ok, and I check that the error start when appears a new dependency using the same version of lizard.

OS and Version: macOS [Xcode Cloud: Ventura 13.6.2 (22G417) - Xcode 14.3.1 (14E300c)]
lizrard-analyzer version 1.17.10

**_Logs - OK:_**

==> Downloading https://ghcr.io/v2/homebrew/core/lizard-analyzer/manifests/1.17.10-3

==> Fetching dependencies for lizard-analyzer: mpdecimal, sqlite and python@3.12

==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1

==> Fetching mpdecimal

==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:91f795d74747bf8723022ac813f3f81d71fefb774116c27f936b2e32018a1926

==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.44.2

==> Fetching sqlite

==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:39b5d014056a8d13c8fe7cb40b3ba9d1112bc0fbfef128c1d31de5c9e27ad007

==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.0-1

==> Fetching python@3.12

==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/blobs/sha256:bb2ff3ad5b25c6981ff89a691bb15f63ff4c978c2bc668f157fadd93fe740baf

==> Fetching lizard-analyzer

==> Downloading https://ghcr.io/v2/homebrew/core/lizard-analyzer/blobs/sha256:054ae8e53fd2a0145ad6be71cd8eb8eceb734a3ef701714f638fd2f65b713d3f

==> Installing dependencies for lizard-analyzer: mpdecimal, sqlite and python@3.12

==> Installing lizard-analyzer dependency: mpdecimal

==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1

Already downloaded: /Users/local/Library/Caches/Homebrew/downloads/f367c2ee08c56b88be0662703a8e4275f8657608a268c8c44e845154b0cea543--mpdecimal-2.5.1.bottle_manifest.json

==> Pouring mpdecimal--2.5.1.ventura.bottle.tar.gz

🍺  /usr/local/Cellar/mpdecimal/2.5.1: 71 files, 2MB

==> Installing lizard-analyzer dependency: sqlite

==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.44.2

Already downloaded: /Users/local/Library/Caches/Homebrew/downloads/1e19b0e6cb419159b49df50f3595c3b44e67ec5f5d1110ece66a9785df57a844--sqlite-3.44.2.bottle_manifest.json

==> Pouring sqlite--3.44.2.ventura.bottle.tar.gz

🍺  /usr/local/Cellar/sqlite/3.44.2: 11 files, 4.7MB

==> Installing lizard-analyzer dependency: python@3.12

==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.0-1

Already downloaded: /Users/local/Library/Caches/Homebrew/downloads/1d0e36aa721b7d8acd766516670f97049b43de5aeca6a81a88fbc208ff4eff5f--python@3.12-3.12.0-1.bottle_manifest.json

==> Pouring python@3.12--3.12.0.ventura.bottle.1.tar.gz

�[34m==>�[0m �[1m/usr/local/Cellar/python@3.12/3.12.0/bin/python3.12 -Im ensurepip�[0m

�[34m==>�[0m �[1m/usr/local/Cellar/python@3.12/3.12.0/bin/python3.12 -Im pip install -v --no-�[0m

🍺  /usr/local/Cellar/python@3.12/3.12.0: 3,193 files, 63MB

==> Installing lizard-analyzer

==> Pouring lizard-analyzer--1.17.10.ventura.bottle.3.tar.gz

🍺  /usr/local/Cellar/lizard-analyzer/1.17.10: 69 files, 204.3KB

==> Running `brew cleanup lizard-analyzer`...

Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.

Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

**_Logs - KO:_**

==> Downloading https://ghcr.io/v2/homebrew/core/lizard-analyzer/manifests/1.17.10-3

==> Fetching dependencies for lizard-analyzer: mpdecimal, sqlite, pkg-config and python@3.12

==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1

==> Fetching mpdecimal

==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:91f795d74747bf8723022ac813f3f81d71fefb774116c27f936b2e32018a1926

==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.44.2

==> Fetching sqlite

==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:39b5d014056a8d13c8fe7cb40b3ba9d1112bc0fbfef128c1d31de5c9e27ad007

==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3

==> Fetching pkg-config

==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:c44b1544815518726d280d92d6f6df09bd45e41ad20fd43424725c1c20760be8

Error: python@3.12: the bottle needs the Apple Command Line Tools to be installed.

Why appears a new dependency with pkg-config?

Thanks in advanced.

**Comment by alnp** [comment]
I'm having the same issue. Were you able to fix it?

**Comment by KeimyPlaza** [comment]
Hi, I fixed added `brew install --build-from-source python@3.12` on top of brew that I need it.
