### ISSUE TITLE
"Cannot find the lizard_languages module."

### ISSUE THREAD

**Issue by ccsyt1205** [terryyin/lizard#392]
Dear author, I downloaded the python package and the lizard package, and I tried to run lizard, but I encountered a problem "Cannot find the lizard_languages module". Just as following:
![image](https://github.com/user-attachments/assets/f5f9d53a-f72e-4e02-89f6-fc01ad5c0c82)
How can I solve it?

**Comment by SshShamma** [comment]
I am also getting this error in latest Lizard version.

**Comment by terryyin** [comment]
I've made a new blank release. Please try again. Let's see if it's a release problem.

**Comment by ccsyt1205** [comment]
I retried on my windows，and it still couldn't work. But it works on Linux.

---- Replied Message ----
| From | Terry ***@***.***> |
| Date | 04/23/2025 14:24 |
| To | terryyin/lizard ***@***.***> |
| Cc | ccsyt1205 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [terryyin/lizard] "Cannot find the lizard_languages module." (Issue #392) |

I've made a new blank release. Please try again. Let's see if it's a release problem.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

terryyin left a comment (terryyin/lizard#392)

I've made a new blank release. Please try again. Let's see if it's a release problem.
