### ISSUE TITLE
Lizard failing on char sequence

### ISSUE THREAD

**Issue by MarkBlaas** [terryyin/lizard#50]
Lizard fails to parse a file when (a form of) the following sequence is encounterd (in regex) [a-zA-Z]<.*>>
So the following sequence is a failing sequence: a<>>

I encounterd the bug when trying to parse a java file with the following line of code:
private static final Map<String, Map<Byte, String>> VAR_NAME = ImmutableMap.<String, Map<Byte, String>> builder()
Although this is really ugly, it is valid java.

I worked around the problem by adding a space between ">>"

**Comment by terryyin** [comment]
Hi @MarkBlaas , I think the issue has been fixed by @rakhimov , do you mind to confirm?

**Comment by rakhimov** [comment]
The problem with C++ templates was triple '>>>'. The given Java example is parsed ok. I don't see any problems though I am not much experienced in Java.

@MarkBlaas, it would be helpful to get the whole file (on github?).

**Comment by MarkBlaas** [comment]
It has been a while :) good to see that it is still worked on. Unfortunately the file is part of some client code, so no can do there. But although i'm pretty busy this week, I'll probably manage to squeeze in some test time. I'll let you guys know what I find.

**Comment by MarkBlaas** [comment]
Hi Guys, it looks like it's fixed indeed. It is a while ago, but I think it was language unrelated, so it could very well be the triple `>>>` issue in C++ although my code was Java.
I dug up some old analysis and compared the results. Here's a summary:
```
Sequence --	Old version --	New version
,A<A,A>>	Fails			Passes
,A<A,>>		Fails			Passes
,A<,>>		Fails			Passes
,<,>>		Passes			Passes
,A<>>		Fails			Passes
a<>>		Fails			Passes
```
Cheers :+1:

**Comment by terryyin** [comment]
great @MarkBlaas let's close this issue. Thanks!
