### ISSUE TITLE
lizard tutorial

### ISSUE THREAD

**Issue by jxieeducation** [terryyin/lizard#57]
Lizard helps me write good code on a daily basis. 

Had some time this weekend to write a simple tutorial / intro http://thrashing.io/tutorial/551891bccfead697722b05ad

Maybe others can find it helpful. Keep up the great work!

**Comment by terryyin** [comment]
Hi Jason,

thanks! I will add a link to it from lizard.ws.

**Comment by kinwahlai** [comment]
Unreachable link, cannot get to the tutorial anymore.

**Comment by terryyin** [comment]
Thanks Kinwah, let me fix it …
