### ISSUE TITLE
Set whitelist via flag

### ISSUE THREAD

**Issue by itavero** [terryyin/lizard#58]
I have the white list for Lizard stored in a different directory than where I run Lizard from (due to build automation).
I would like to see an option to pass a white-list to Lizard via a special command line flag.

**Comment by terryyin** [comment]
Let me add it ...

**Comment by terryyin** [comment]
Use -W filename
I've created a new release 1.8.11 for this.

**Comment by itavero** [comment]
Woow! Thanks for the quick response and change! :+1:
