### ISSUE TITLE
Swift langage support

### ISSUE THREAD

**Issue by kenji21** [terryyin/lizard#61]
We are using lizard on objc project (thanks you for this nice tool that improve xcode using a simple script), is there any chances that brand new Swift language will be supported ?

I have no idea on how to add support for it, maybe some indication will help to support it.

**Comment by terryyin** [comment]
Great idea! I’m going to implement it next week after I study the language a bit.

**Comment by kenji21** [comment]
Wow, nice :-D

**Comment by terryyin** [comment]
Hi @kenji21 ,
it has been a while. I finally did something with Swift.
I added a new option -l, which can filter the languages:
   lizard -lswift <folder_name>

will analyse swift code only, otherwise it will process all file types it knows.

This is only a draft version for Swift support. I’m not sure if it’s completed yet. I don’t know much about Swift myself. 
There’s at least one open issue, there seems to be nested functions in Swift, 
is it common?
How do you want to count for nested functions?

terry

**Comment by kenji21** [comment]
Hi terry, nice to have some advancement on this.

Unfortunately I haven't switched to fulltime dev using swift yet. So I can't respond to your question.

Maybe having a look at these "swift grammar" files of the tailor project can help : https://github.com/sleekbyte/tailor/tree/master/src/test/swift/com/sleekbyte/tailor/grammar

**Comment by terryyin** [comment]
Thanks!

**Comment by kenji21** [comment]
Cool, it also can find swift an objc issues :

````
lizard --CCN 12 --ignore_warnings 20 --working_threads 4 -w
./ATvhClient/EPGCollectionViewLayout.swift:12: warning: durationInHourForItemAtIndexPath has 16 CCN and 1 params (71 NLOC, 595 tokens)
./tvheadend-ios-lib/tvheadend-ios-lib/SSHWrapper.m:214: warning: setPortForwardFromPort: toHost: onPort: has 29 CCN and 0 params (134 NLOC, 853 tokens)
````

**Comment by terryyin** [comment]
There’s also a new option -l to select the language, e.g.
lizard -lswift -lobjc

will only search for swift and objective-c code.

**Comment by kenji21** [comment]
Ok, surprising that the EPGCollectionViewLayout.swift:12 is a method of an interface :

````
protocol EPGCollectionViewLayoutDelegate {
    func durationInHourForItemAtIndexPath(indexPath: NSIndexPath) -> Double
    func startDateForItemAtIndexPath(indexPath: NSIndexPath) -> NSDate
}
````

**Comment by terryyin** [comment]
Congrats! you just found a bug! Thanks.

I thought adding Swift shouldn’t be that easy… I will fix it asap.

**Comment by terryyin** [comment]
Hi @jenji21 ,

I just made a new release. It will be great if you can try it at your convenience.

terry

**Comment by kenji21** [comment]
Just tried, now it's on the next method of the protocol :

````
lizard  --CCN 12 --ignore_warnings 20 --working_threads 4 -w
./ATvhClient/EPGCollectionViewLayout.swift:13: warning: startDateForItemAtIndexPath has 16 CCN and 1 params (70 NLOC, 585 tokens)
````

**Comment by terryyin** [comment]
do you mind send me the file or the context?

**Comment by kenji21** [comment]
Sure, this project will be open-sourced soon :-)


[EPGCollectionViewLayout.swift.zip](https://github.com/terryyin/lizard/files/63820/EPGCollectionViewLayout.swift.zip)

**Comment by terryyin** [comment]
thanks for sharing.

Now the problem is fixed.

**Comment by kenji21** [comment]
Cool, seems to work well on Apple Lister sample:

https://developer.apple.com/library/ios/samplecode/Lister/Introduction/Intro.html

**Comment by terryyin** [comment]
@foobra could you also provide the swift code?

**Comment by foobra** [comment]
@terryyin 
`extension HomePageTimelineVC: UITableViewDataSource, UITableViewDelegate {
    public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        switch viewModel.vms[indexPath.row] {
            case let model as TimelineCellPhotoViewModel:
                let cell = tableView.dequeueReusableCell(withIdentifier: TimelineCellPhoto.className) as? TimelineCellPhoto
                           ?? TimelineCellPhoto(.timeline, style: .default, reuseIdentifier: TimelineCellPhoto.className)
                cell.configCell(viewModel: model, vc: self)
                return cell
            case let model as TimelineCellVideoViewModel:
                let cell = tableView.dequeueReusableCell(withIdentifier: TimelineVideoCell.className) as? TimelineVideoCell
                           ?? TimelineVideoCell(.timeline, style: .default, reuseIdentifier: TimelineVideoCell.className)
                cell.configCell(viewModel: model, vc: self)
                return cell

        default:
            fatalError()
        }
    }

    public func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return viewModel.vms.count
    }

    public func tableView(_ tableView: UITableView, didEndDisplaying cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if let model = viewModel.vms[indexPath.row] as? TimelineCellVideoViewModel {
            model.state.playerPauseProxy?()
        }
    }
}
`

lizard -l swift -s cyclomatic_complexity -X demo.swift

**Comment by foobra** [comment]
@terryyin can we fix that?

**Comment by terryyin** [comment]
@pinguo_gaoshan if you know the solution, please send a pull request (don’t forget the tests).

I won’t have time to look at this at least for this week (weekend maybe).

**Comment by nhkrishna5** [comment]
Hi @terryyin 
How to create the custom file, to override  "cyclomatic complexity number". In iOS Swift.

Like mentioned in 
-T THRESHOLDS, --Threshold THRESHOLDS
                      Set the limit for a field. The field can be nloc, cyclomatic_complexity,
                      token_count, parameter_count, etc. Or an customized file. Lizard will
                      report warning if a function exceed the limit
