### ISSUE TITLE
about filename in whitelizard.txt

### ISSUE THREAD

**Issue by mythnc** [terryyin/lizard#62]
Actually, it's path not filename.
You have to type the path instead of only filename.
I think the explanation in readme is too vague

**Comment by terryyin** [comment]
Hi @mythnc ,
Thanks for the idea and sorry for the super late reply.
I've updated the README and added "Please notice that if you assign the file pathname, it need to be exactly the same relative path as Lizard find the file. An easy way to get the file pathname is copy it from the Lizard warning output."

I also updated the example a bit.

**Comment by mythnc** [comment]
Thank you for updating :+1:
