### ISSUE TITLE
C++11 Uniform Init. within constructor Initialization list

### ISSUE THREAD

**Issue by rakhimov** [terryyin/lizard#64]
C++11 '{}' for uniform initialization
in constructor initialization list
seems to break some assumptions in the code
that the definition starts with the first brace.

**Comment by terryyin** [comment]
Hi,
I really need to learn C++11 more systematically:-)
It's solved and I'm going to create a new release.

Terry

**Comment by rakhimov** [comment]
Thanks for fixing it fast.
