### ISSUE TITLE
Detection of Deeply Nested Control Structures

### ISSUE THREAD

**Issue by rakhimov** [terryyin/lizard#69]
This metric may not apply to the whole function,
but the maximum 'nestedness' (nesting for-loops, if-statements, etc.)
may be an interesting metric to detect code smell.

It closely relates to indentation. 
Got this from the Linux kernel coding style:
>The answer to that is that if you need
more than 3 levels of indentation, you're screwed anyway, and should fix
your program.

**Comment by mehrdad89** [comment]
Hi @terryyin! 
I think this metric will be a great addition to this awesome tool. I'm gonna do it!
Hopefully, I can finish it this weekend.
