### ISSUE TITLE
Qualify C++ functions with namespace and class names

### ISSUE THREAD

**Issue by rakhimov** [terryyin/lizard#70]
Currently, the following code will produce the same function signatures for reporting.
```cpp
struct A { bool operator()(int) {...} };
struct B { bool operator()(int) {...} };
```
It would be beneficial to have class name and/or namespace attached to the function names.

**Comment by rakhimov** [comment]
It is not clear if all instances of function definitions should be qualified. There are some tricky cases with C++.

- Class/struct within a function (the qualification may need to include the function name):
```cpp
void foo() { struct A { void bar() {} }; }
```
- Lambda functions (unnamed closure/class in C++11):
```cpp
void foo() { auto bar = [](){ return 42; } }
```

**Comment by terryyin** [comment]
@rakhimov , this looks like JavaScript!
Hmmm, I've actually been thinking what measurement would make sense for JavaScript nested functions, which aren't corner cases at all for js.
So far, lizard will just ignore them. But I think maybe we should add the ability of detecting them before we can decide how to measure.

**Comment by rakhimov** [comment]
Can the complexity of the inner constructs be just silently added to the complexity of the outermost construct?

**Comment by rakhimov** [comment]
The Lizard analysis of Python code with nested functions reports each function separately with line number information. Is this the same behavior across other languages?

**Comment by terryyin** [comment]
Adding to the outermost construct makes a lot of sense. Let me do it.
The Python nested function was implemented separately, unfortunately. I will see if I can merge the implementation.

**Comment by tobias-klein** [comment]
@terryyin Has there been any work on this since last October? I think this would be a very useful enhancement.

**Comment by terryyin** [comment]
Hi @tobias-klein thanks for getting back to this. The last Oct 17 commit already does most of the namespace work https://github.com/terryyin/lizard/commit/eb95a74ae2ac02763a7f4f6736f34225cbca69a6 .

And now it is like @rakhimov said that the inner structure or lambda add complexity to the outermost function.

But if you are referring to the javascript nesting, there hasn't been any progress yet. So what do you want?

**Comment by rakhimov** [comment]
I feel sorry for C++ compiler designers.
Working on 'nesting_level' and 'nested_structures' metrics,
I have been discovering horror-inducing constructs that is possible in C++.
These constructs relate to this issue as well.
Consider this example:

```cpp
  for (struct {int s;int foo() { while(true) break;  return 42;}} a{42};;) break;
```

That's unnamed struct that can have arbitrary complexity
in addition of being inside for-loop declaration.
I bet McCabe couldn't have imagined this sort of complexity.

**Comment by terryyin** [comment]
@rakhimov thanks for demoing the complex C++ code. If everybody is happy with the current status I will close this issue.

**Comment by rakhimov** [comment]
Hi @terryyin ,
can you document the current approach? (In ``theory.rst`` maybe.)
I am not sure if the additive approach has already been implemented.
I am in favor of ignoring nested structs and classes only inside functions for now
until someone comes up with something smarter.

**Comment by terryyin** [comment]
Some theory added.

**Comment by tobias-klein** [comment]
Thanks @terryyin 
I was just wondering, why this was still open...
