### ISSUE TITLE
output html

### ISSUE THREAD

**Issue by terryyin** [terryyin/lizard#76]

**Comment by terryyin** [comment]
Yep, do you know how to merge issues?

**Comment by rakhimov** [comment]
You reference & close duplicates :)
That's the only way I know.

**Comment by terryyin** [comment]
Cool. I'm having a 6.5-hour flight ahead. Will work on something then. Not likely to be this one though.

**Comment by rakhimov** [comment]
@terryyin I think you need to keep this 'original' issue open and close the duplicate #195 .

**Comment by terryyin** [comment]
Yes, but this time I created the original long time ago. So want to keep the ‘real request’ open.
