### ISSUE TITLE
pip install fails building wheel for hfcca

### ISSUE THREAD

**Issue by jbiswas** [terryyin/lizard#85]
I am trying to install lizard on a debian 8.0 machine. But I get the following error when running `sudo pip install lizard`

```
  running install_egg_info
  running egg_info
  writing hfcca.egg-info/PKG-INFO
  writing top-level names to hfcca.egg-info/top_level.txt
  writing dependency_links to hfcca.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'hfcca.egg-info/SOURCES.txt'
  writing manifest file 'hfcca.egg-info/SOURCES.txt'
  Copying hfcca.egg-info to build/bdist.linux-x86_64/wheel/hfcca-1.9.18-py2.7.egg-info
  running install_scripts
  ...
  copying build/lib.linux-x86_64-2.7/languages/java.py -> build/bdist.linux-x86_64/wheel/languages
  error: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/wheel/languages/java.py'

  ----------------------------------------
  Failed building wheel for hfcca
  Running setup.py clean for hfcca
Failed to build hfcca hfcca
ERROR: Failed to build one or more wheels
```
After that if I try to display this error again I must run `sudo pip wheel lizard`

**Comment by terryyin** [comment]
Sorry for the late response, traveling in Seoul for a week.

@jbiswas did you mean that after `sudo pip wheel lizard` it worked?

**Comment by jbiswas** [comment]
@terryyin thanks for getting back to me. No running `sudo pip wheel lizard` didn't work. I had to run `sudo pip install hfcca` to get lizard. Even then the ouput of pip install contained the same errors as above. But at least I can run `lizard`.

**Comment by terryyin** [comment]
Could you please try again and see if the problem is fixed?

I didn't enable wheel in the previous releases. I hope it's working now.

**Comment by jbiswas** [comment]
@terryyin wow it works in version 1.9.22. Thanks very much!
