### ISSUE TITLE
Request: Ability to specify NLOC threshold

### ISSUE THREAD

**Issue by pricemi115** [terryyin/lizard#86]
Thank you for this tool :)
I am using this to ensure our code meets the CCN & NLOC requirements of our coding standard.
It would be nice if we could specify a threshold for NLOC like we can for CCN, To my team, NLOC is a better criterion than raw length. I took the liberty of modifying my local lizard.py (v1.9.22) to do this.
See attached,
[lizard.py.txt](https://github.com/terryyin/lizard/files/107430/lizard.py.txt)

**Comment by terryyin** [comment]
Thanks @pricemi115 yes, I agree it's very useful.
Do you want to make a proper "pull request"? by fork my repository and make the change then send pull request. By doing this you will be listed as the contributor for this part:-)
Or you are fine that I just copy your code?

Reminder: if you send pull request, better also add enough test:-)

**Comment by pricemi115** [comment]
If you copy the code that would be easier. The credit really belongs to you anyway. It was a pretty easy mod :)

**Comment by terryyin** [comment]
@pricemi115 In stead of add a new option `N`, I added a new option `T`.

`lizard -Tnloc=10`

will set the threshold for NLOC to be 10. A new release has been created, you can try now.

**Comment by pricemi115** [comment]
Awesome!! We will try it out tomorrow or early next week.
Thank you :)
