### ISSUE TITLE
sys.exit(1) not called when "warnings only" enabled

### ISSUE THREAD

**Issue by pricemi115** [terryyin/lizard#87]
When invoking lizard via a command prompt on Windows, the Error level is not set to 1 when warnings are found, but the --warnings_only argument is specified. 

Looking at the script, it appears that since print_result() is not called, the error condition is never set.
Probably need to set "sys.exit(1)" in print_clang_style_warning() as well.

**Comment by terryyin** [comment]
Oops, this is a major problem from last time I refactored the code. Obviously I didn't have enough test.

Thanks. Fixing...

**Comment by terryyin** [comment]
OK. Now it's fixed in the latest release.

**Comment by pricemi115** [comment]
Fantastic !! Thank you :)

**Comment by pricemi115** [comment]
Hi Terry:

Just wanted to let you know that v1.9.25
addresses both issues: the new threshold features and the --warnings_only issue.

Thank you very much!!

Take care,
Mike Price.

**Comment by terryyin** [comment]
Great:-)
