### ISSUE TITLE
Issue analyzing C code with preprocessor directives

### ISSUE THREAD

**Issue by wsnavely** [terryyin/lizard#88]
I've been having issues with C code involving preprocessor directives, e.g. consider this toy function:

```
int foo(int a, int b) {
    if(a == b) {
#ifdef BAR
        if(b == 10) {
#else
        if(b == 11) {
#endif         
            return 0xFF;
        }
    }
    return 0;
}
```
lizard won't parse this function by default, I believe because it can't account for all the brackets (both branches of the #ifdef introduce an open bracket).
  
Is this expected?  I see there is an -Ecpre flag that seems to help in some cases (though I'm not entirely clear what that flag does), but I had thought this sort of code would be parseable without special flags.  

Thanks!

**Comment by terryyin** [comment]
@wsnavely yes, this is expected. Because there are more {s than }s.
And you are right, -Ecpre is designed for this purpose. -Ecpre works by always ignoring code between #else and #end (always assume the #if condition is true).

The document (including the docstring) isn't great about this. Let me improve it.

Any idea to make this better?

**Comment by wsnavely** [comment]
Thanks for the response, @terryyin.

I understand the -Ecpre tag better now, but I think that feature has an issue as well.  It doesn't seem to like code like this:

```
void foo() {
#if defined(BLAH1)
// do something
#elif defined(BLAH2)
// do something else
#elif define(BLAH3)
// do a third thing
#endif
}

It won't find the function.  I feel like this is related to the code on line 21 of lizard_ext/lizardcpre.py
```
                    elif token.startswith("#endif"):
                        if if_stack and if_stack.pop().startswith("#el"):
                            else_count -= 1
                            if if_stack:
                                if_stack.pop()
```

**Comment by terryyin** [comment]
This is a bug in the implementation. I've fixed it and included it in the newest release.

Thanks! 
The method `preprocess_tokens` now has a CCN of 9...

**Comment by terryyin** [comment]
This is now fixed, right?
