### ISSUE TITLE
XML Output Missing Information

### ISSUE THREAD

**Issue by vsiddharth** [terryyin/lizard#90]
The XML output from the tool is **missing** critical information which is present in the text output. 
It would be wonderful if both formats had all the information.

**Comment by terryyin** [comment]
@vsiddharth thanks for the information, let me add them.

**Comment by vsiddharth** [comment]
@terryyin thanks!
It would be wonderful if you could also have **tags** or **releases**.

**Comment by JiahangLi** [comment]
Agreed.  The summary of data, i.e. Function Avg CCN, Fun Avg NLOC, would be super helpful. 
The sum of each metrics won't be as helpful as a function based metrics: [http://www.drdobbs.com/architecture-and-design/measuring-complexity-correctly/240007928]

I can do a easy math by using total CCN/ total # func = Avg CCN per func, but it seems easier for the rest of team just to see it directly. 

Thanks for creating such an awesome tool! I used it to analysis our team data and it is making people decide to improve their code! Big thanks
