### ISSUE TITLE
Incorrect Function Length Computation

### ISSUE THREAD

**Issue by vsiddharth** [terryyin/lizard#91]
Currently:
Function-Length = End_Marker - Begin_Marker

But the correct computation would be:
Function-Length = End_Marker - Begin_Marker + 1

**Comment by terryyin** [comment]
You are right. This is fixed with NLOC but not LOC. Fixing...

**Comment by terryyin** [comment]
I've fixed it. Will group it will some other small fixes and create a new release this week.

**Comment by terryyin** [comment]
OK. It's now included in the latest release.
