### ISSUE TITLE
suport PHP

### ISSUE THREAD

**Issue by terryyin** [terryyin/lizard#92]

**Comment by iconnor** [comment]
@terryyin this would be great!

**Comment by mikesive** [comment]
@terryyin seconded

**Comment by tobias-klein** [comment]
@terryyin Yes, please add that! :)

**Comment by terryyin** [comment]
C# has been added. I'm going to close this issue and see if anybody would create an issue for the missing of PHP.

**Comment by mikesive** [comment]
Hey @terryyin I am really keen for PHP support as PHPMD is very slow. Is it possible to do PHP as well? I had hoped the bounty on bountysource applied to both PHP and C#.

**Comment by terryyin** [comment]
OK, I've reopened the issue and change the title.

@mikesive I'm going to give PHP a try, but can not be very sure this time. Because PHP can be also inline in HTML. All the other languages are tokenised as the fist step. But I guess with PHP probably some other preprocessing need to be done before tokenising.

we'll see:-)

**Comment by mikesive** [comment]
Thanks @terryyin look forward to seeing how you go.

**Comment by terryyin** [comment]
@mikesive , I've added PHP and created a new release in PyPI (1.12.0).
It will be great if you can help to verify it.
If you want to run lizard for PHP only, do

    lizard -lphp

I will improve the PHP support to add things like "namespace" (class names). But I think the basic function is there already now.

The commits did the job are:
https://github.com/terryyin/lizard/commit/69336258c2f1cf4c3592a1fa44da6d0091459865
https://github.com/terryyin/lizard/commit/539566d37862902c4068e14e0a7d732827469a99
https://github.com/terryyin/lizard/commit/0ae15e11301a9a79cab2d89bc13e2b0c2bf804a7

**Comment by mikesive** [comment]
@terryyin looks good! I had a quick run through today, very fast compared to other PHP tools. I will test more thoroughly tomorrow. Thanks for getting this done!

**Comment by iconnor** [comment]
This works for us! I think you can close it now @terryyin

**Comment by terryyin** [comment]
Great!
