### ISSUE TITLE
cyclomatic complexity (&&) bug in clike

### ISSUE THREAD

**Issue by mehrdad89** [terryyin/lizard#98]
HI! 

I am currently writing tests to find bugs in nesting depth metric which I soon commit to this project however as of now (lizard 1.10.4) there is a problem with cyclomatic complexity counting down (&&) in this unit test.

    def test_one_function_with_statement_no_curly_brackets(self):
        result = get_cpp_function_list("""
        x c() {
        if (a > -1 && b>= 0 )
              if(a != 0)
                    a = b;
        }
        """)
        self.assertEqual(4, result[0].cyclomatic_complexity)

I think it has a direct contradiction with the (test_one_function_with_r_value_ref_in_body) unit test .

**Comment by terryyin** [comment]
Hi @mehrdad89 sorry I overlook your message (the preview of the email has only "Hi!") I'm looking at it...

**Comment by terryyin** [comment]
@mehrdad89 you are right, the bug is introduced when I made the solution for r_value_ref. It's now fixed with https://github.com/terryyin/lizard/commit/2a165bdd1cb1b318a15bf6b1bfdce8bcc32d70df
I will create a new release next week.

thanks for the reporting.

**Comment by mehrdad89** [comment]
thank for the reply! 
Actually I just finished coding a new metric (nesting depth metric) into lizard.
At the moment, it is only supporting clike and python. Hopefully if all test are done I will be pushing it to your repository today.

**Comment by terryyin** [comment]
Great! Cannot wait (but it’s bed time here).

BTW, adding tests after the implementation sounds really boring:P

**Comment by mehrdad89** [comment]
Yeap! tell me about it!
